version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tournament_db
    ports:
      - "5432:5432"
    volumes:
      - tournament_db_data:/var/lib/postgresql/data

volumes:
  tournament_db_data:
